### ISSUE TITLE
Integration with Calcite

### ISSUE THREAD

**Issue by ChrisMahlke** [Esri/global-nav#13]
I created a prototype and only pulled in [Calcite Web](http://esri.github.io/calcite-web/) and Esri's JS API 3.19.

Prototype
https://chrismahlke.github.io/esri-global-nav/dist/

I'm seeing some styling issues related to Calcite integration in all modern browsers (screen shots below from Edge):

**Dropdown menu**
![esri-global-nav-dropdown-calcite-bugpng](https://cloud.githubusercontent.com/assets/4925379/22678797/a792f454-ecb1-11e6-923b-69aa0fc7de30.PNG)

**Blue background on mouseover**
![esri-global-nav-moseover-calcite](https://cloud.githubusercontent.com/assets/4925379/22678812/c33d7526-ecb1-11e6-8454-28173a7a435e.PNG)

@jonathantneal is there something I missed in the doc related to pulling in Calcite?  Should it work out-of-the-box with Calcite without any extra configuration(s)?

@TamaraYoder

**Comment by ChrisMahlke** [comment]
@jonathantneal  Was anyone able to get the global nav to work with the latest version of Calcite?

cc @sanjibpanda @mharrower @cscopel

**Comment by dlewis-esri** [comment]
Yea we have it running on esri.com and it has calcite 1.0.0-rc.4 running on it
