### ISSUE TITLE
Footer's social-media icons assume English labels; translated labels don't highlight upon hover

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/global-nav#134]
In file footer\js\footer-social.js, a social-media icon is given its lower-case label as a class: 
```
class: `${prefix}-social-link -${item.label.toLowerCase()}`
```
and footer-social.pcss uses this to make a product-specific background color change during a hover:
```
&.-linkedin:--enter {
	background-color: #127cb3;
}
```

If the label is translated, e.g., "ينكدين", you end up with a class name that is not defined in footer-social.pcss, e.g.,
```
<a class="esri-footer-social-link -ينكدين" href="https://www.linkedin.com/company/esri" aria-label="ينكدين"></a>
```
and so you don't get the hover behavior.

Label is not displayed, so this issue affects only ARIA usage and only for languages that translate one or more of the social media brand names.

**Comment by paulcpederson** [comment]
@MikeTschudi you can now pass an additional property `platform` as well as a label. The class will use platform, only falling back to using the label if `platform` is unavailable:

```javascript
{
  label: 'ينكدين',
  platform: 'linkedin',
  href: 'https://www.linkedin.com/company/esri',
  image: {
    viewBox: '0 0 38 38',
    path: ['M0 0v24h24V0zm8 19H5V8h3zM6.5 6.7A1.8 1.8 0 1 1 8.3 5a1.8 1.8 0 0 1-1.8 1.7zM20 19h-3v-5.6c0-3.4-4-3.1-4 0V19h-3V8h3v1.8c1.4-2.6 7-2.8 7 2.5z']
  }
}
```
