### ISSUE TITLE
Switch Account button

### ISSUE THREAD

**Issue by ChrisMahlke** [Esri/global-nav#165]
Are there any samples or is there any guidance on how the **Switch Account** button in the dropdown is suppose to work?   I can create an event listener for it:

`esriHeader.addEventListener('header:click:switch', _switchClickHandler);`

But then I'm not sure what to do.   Is there a re-direct url I need to point to?

**Comment by jpeterson** [comment]
@ChrisMahlke I'm in the same spot – could you share your solution? Thanks!
