### ISSUE TITLE
Accessibility: Nav <li> elements must be in a <ul> or <ol>

### ISSUE THREAD

**Issue by capeoples** [Esri/global-nav#234]
Per axe accessibility report. This applies to all left-aligned text links. 

![Screen Shot 2019-05-08 at 10 41 44 AM](https://user-images.githubusercontent.com/30473086/57395825-e3e81800-717d-11e9-833a-dca0d0e967c3.png)

**Comment by paulcpederson** [comment]
I think this might be fixed in the most recent version: https://esri.github.io/global-nav/
