### ISSUE TITLE
Shopping Cart is Showing up Everywhere

### ISSUE THREAD

**Issue by gschnall** [Esri/global-nav#240]
The shopping cart shows up on the navbar in Online after updating the submodule. This happens even though `detail.cart` is set to `undefined`. The `header:update:cart` event also never fires.  Shows up on map maker and other apps too.

cc @paulcpederson @kevindoshier 

![Screen Shot 2019-06-12 at 12 20 23 PM](https://user-images.githubusercontent.com/15697698/59381015-55802c80-8d0f-11e9-9487-1cccd0bacdfc.png)

**Comment by paulcpederson** [comment]
There should also be no badge when count is zero, IMO

**Comment by dlewis-esri** [comment]
@maccesar21 is looking into this now

**Comment by paulcpederson** [comment]
Feel free to reopen if this is still an issue, but I think it got taken care of.
