### ISSUE TITLE
Convert to Web Component

### ISSUE THREAD

**Issue by julio8a** [Esri/global-nav#249]
We've built a web component library, which is framework agnostic (ember, react, angular, etc.) [calcite-components](https://github.com/Esri/calcite-components). It would be great to have the global-nav as a web component as well and follow the same structure as the calcite-components since they will likely be used together and we want to make the dev experience consistent for users.

**Comment by paulcpederson** [comment]
Work underway on this on the 2.0 branch. Here is a summary of progress for those interested:

First passes on all component conversions:
- [ ] esri-footer
- [ ] esri-footer-brand
- [ ] esri-footer-breadcrumbs
- [ ] esri-footer-language
- [ ] esri-footer-social
- [x] esri-header
- [x] esri-header-account
- [x] esri-header-apps
- [x] esri-header-brand
- [x] esri-header-cart
- [ ] esri-header-inline-search
- [ ] esri-header-inline-title
- [ ] esri-header-menus
- [x] esri-header-notifications
- [x] esri-header-search

Feature Parity TODO:
- [ ] Dir (rtl)
- [ ] Responsive (ensure works across screen sizes)
- [ ] Audit all current events, ensure coverage
- [ ] App switcher drag and drop
- [ ] Documentation

---

New Feature TODO:
- [ ] Dark Mode
- [ ] Tests

**Comment by paulcpederson** [comment]
Closing in favor of upcoming stencil-based calcite navigation
