### ISSUE TITLE
Security: Hardcoded Domain

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [Esri/global-nav#251]
It's unsafe use  untrusted control sphere，please refer to CWE-829 https://cwe.mitre.org/data/definitions/829.html

https://github.com/Esri/global-nav/blob/0d7be78062c07fc64e4f16313eeff496cf1747c9/src/index.html#L597

**Comment by paulcpederson** [comment]
Should be fixed in [📦  v1.4.0](https://github.com/Esri/global-nav/releases/tag/v1.4.0)
