### ISSUE TITLE
Update to edit mode from static mode

### ISSUE THREAD

**Issue by kevindoshier** [Esri/global-nav#253]
Id like to set the title to editable, and update the title, after being created as non-editable, I tried this

`const event = document.createEvent("CustomEvent");
      event.initCustomEvent("header:update:inlineTitle", true, true, {
        label: newTitle,
        brandText: newTitle,
        editTitle: true
      });

titleNode.dispatchEvent(event); `

And see this
![image](https://user-images.githubusercontent.com/11093161/65396212-bd0b3680-dd58-11e9-93ab-788a4cad6ca1.png)

**Comment by kevindoshier** [comment]
The use case for us is that we begin by viewing a map that we cannot edit, however this map allows saving copies of it by other users, we save a copy and now own the map, and therefore can edit the title of it, and need the header to reflect that

**Comment by paulcpederson** [comment]
I've made it so you can dispatch a sparse object to `header:update` after the initial page load. If you pass a `brand` with `editTitle: true` it will initialize a new inline-edit title and destroy the old static title. Will be part of #264

```
const event = document.createEvent("CustomEvent");
event.initCustomEvent("header:update", true, true, {
  brand: {
    editTitle: true,
    brandText: "Map title"
  }
});
document.querySelector(".esri-header").dispatchEvent(event);
```

**Comment by kevindoshier** [comment]
@paulcpederson - thanks, just tested this and its working great
