### ISSUE TITLE
Incorporate App Switcher

### ISSUE THREAD

**Issue by gschnall** [Esri/global-nav#26]
@jonathantneal Placing this as an issue for reference.

A vanilla javascript version of the app switcher is located in a repo on Devtopia:
[https://devtopia.esri.com/gabe8788/ago_app_switcher](https://devtopia.esri.com/gabe8788/ago_app_switcher)

The most complex issue we'll face, in regards to integrating it, is providing the app switcher with the following information. 

```js 
var data = {
   "username": "jeff",
   "orgUrlKey": currentUserOrgUrlKey,
   "appTitle": "arcgis online",
   "environment": "devext" // or qa or production (if set to null, this will default to production) 
 };

AgoAppSwitcher.init(data);
```

It's up to the application to provide this data for the global-nav. So we could simply say, if the username, orgUrlKey, or appTitle are null or not provided within the apps object, the app switcher doesn't get displayed. 

Both the minified and unminified versions of the css and javascript are included in the repo. Feel free to edit them.

**Comment by bstifle** [comment]
@jonathantneal Not quite.

This project is in the works. looping in @HeathMeyette
