### ISSUE TITLE
Fallback To HTML Text as Substitute for the Brand Image

### ISSUE THREAD

**Issue by gschnall** [Esri/global-nav#27]
In Brand, if no image is provided, default to using label text instead.

```json
brand: {
  label: 'ArcGIS'
}
```

Alternatively, we could provide something other than label

```json
brand: {
   label: 'ArcGIS',
   logoText: 'ArcGIS'
 }
```

This is important for ArcGIS online, as you see this kind of text displayed on map and scene viewer as well.

![screen shot 2017-07-18 at 4 17 52 pm](https://user-images.githubusercontent.com/15697698/28343947-23469e14-6bd5-11e7-867b-6378c748d5c1.png)

![screen shot 2017-07-18 at 4 17 20 pm](https://user-images.githubusercontent.com/15697698/28343949-256190b4-6bd5-11e7-937f-69b5e05b86e2.png)

**Comment by bstifle** [comment]
ArcGIS should be an SVG. Shouldnt My Map be Map Viewer? @asangma
