### ISSUE TITLE
In mobile view, adjust alignment of product name to be centered

### ISSUE THREAD

**Issue by capeoples** [Esri/global-nav#274]
In mobile views, the product name is off center.

![Screen Shot 2020-01-16 at 12 30 27 PM](https://user-images.githubusercontent.com/30473086/72560529-12b1a480-385c-11ea-9451-dc487c8b6bb6.png)

Just want to update this so that it's centered!

**Comment by paulcpederson** [comment]
Should be fixed in [📦  v1.4.0](https://github.com/Esri/global-nav/releases/tag/v1.4.0)
