### ISSUE TITLE
Accessibility: `aria-expanded` used in desktop header menu

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/global-nav#305]
Level Access' [Continuum Explorer Community](https://www.webaccessibility.com/) tool reports that "The aria-expanded attribute is not allowed on this..." for the desktop header menu.

It is allowed on the mobile header menu because it is collapsible. 

Easily solved by removing the attribute just from the desktop variant

**Comment by paulcpederson** [comment]
Should be fixed in [📦  v1.4.0](https://github.com/Esri/global-nav/releases/tag/v1.4.0)
