### ISSUE TITLE
Accessibility: account dropdown doesn't capture focus

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/global-nav#306]
Tabbing through account dropdown, the tab position after "Sign Out" is outside of the account dropdown.

![image](https://user-images.githubusercontent.com/2125181/86927735-8c7a6a80-c0e8-11ea-8e66-ca0259501d9d.png)

It seems that the account window should behave like a [modal dialog](https://www.w3.org/TR/wai-aria-practices-1.2/#dialog_modal), so, when tabbling, "If focus is on the last tabbable element inside the dialog, moves focus to the first tabbable element inside the dialog". Since the button that opens the dialog is the same as the one that closes it without any other action, it seems that the first tabbable element should be the button.

**Comment by paulcpederson** [comment]
A fix for this was merged in, I believe.
