### ISSUE TITLE
Links in documentation are broken

### ISSUE THREAD

**Issue by paulcpederson** [Esri/global-nav#309]
The links in the top nav on https://esri.github.io/global-nav/ are now buttons, rather than links. Not sure if the API changed?

Not sure why? There has been some churn lately, maybe they just need redeployed.

**Comment by dlewis-irse** [comment]
We did change anything that did not send you to another url from a link to a button - this was for accessibility, @maccesar21 is going to look into the preview page and see why it's not working

**Comment by paulcpederson** [comment]
This is fixed and deployed now
