### ISSUE TITLE
Documentation: how to make footer optional

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/global-nav#315]
The "Initialize" example on the page https://esri.github.io/global-nav/ implies that the footer is optional:

```json
  // Object representing the structure of the entire footer (optional)
  footer: {
    hideMenus: false,
```
Until 1.4.0, we could achieve this with the following footer definition:
```json
"footer": {
  "hideMenus": true,
  "label": "",
  "brand": {
    "label": null,
    "href": null,
    "viewBox": null,
    "path": ""
  },
  "menu": {
    "label": null,
    "menu": [ {
      "label": null,
      "menu": [ ]
    } ]
  },
  "social": {
    "label": null,
    "menu": [ ]
  },
  "info": {
    "label": null,
    "menu": [ ]
  }
}
```

This definition produces a11y errors:
![image](https://user-images.githubusercontent.com/2125181/90448570-77efa180-e09a-11ea-9f19-4fb4836bfe74.png)
because `aria-label` is set to `null`.

How can we not use the footer, please? Currently, we delete the element with the id "esri-footer-barrier".

**Comment by paulcpederson** [comment]
You could use `esriGlobalNav.createHeader()` rather than `esriGlobalNav.create()`, I think. 

We should fix this a11y error, though. I can do to the footer what I did to the header where elements not defined in the config are hidden from screen readers.

**Comment by MikeTschudi** [comment]
@paulcpederson, excellent suggestion to use `createHeader` only--thank you. Works perfectly.

**Comment by paulcpederson** [comment]
Cool, glad that worked for you.  I'll continue to poke around on the original issue 👍
