### ISSUE TITLE
Enh: please consider adding .d.ts file to dist folder

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/global-nav#316]
That way, we can include esri-global-nav in a package.json file
```json
"esri-global-nav": "github:esri/global-nav#v1.4.1",
```
and get the typing along with the .js in node_modules.

**Comment by paulcpederson** [comment]
#317

**Comment by paulcpederson** [comment]
should be in 📦 v1.4.2

**Comment by MikeTschudi** [comment]
Thank you, @paulcpederson!
